version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
        - ./:/etc/nginx/html
        - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - vue

  vue:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    working_dir: /vue