version: '3'

services:
  nginx:
    image: nginx:1.13
    ports:
      - "80:80"
    volumes:
        - ./:/etc/nginx/html
        - ./.nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./:/etc/nginx/html